# data
source_root = "src/data/source_data"
target_root = "src/data/target_data"                                        # if running multiple experiments, rename this if you want to preserve the prvsly generated dataset
# hyperparameters 
scale = [0.1]                                                       # scaling factor by which to multiply Height and Width image dimensions by for compression
sigma = [20]                                                           # STD of the gaussian distributed noise added 
kernel = ["bilinear_gaussian_noise","nearest_neighbor_gaussian_noise"]      #  "nearest_neighbor_gaussian_noise" or "bilinear_gaussian_noise"

# training
epochs = 5
batch_size = 4
img_size = 640

# model weights
yolo_weights = "yolo12l.pt"
rtdeter_weights = "rtdetr-l.pt"

